"""added columns to document table

Revision ID: 05665c398dc2
Revises: 7614e238a93e
Create Date: 2026-03-24 03:05:38.195111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05665c398dc2'
down_revision: Union[str, None] = '7614e238a93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('warning_task_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('deletion_task_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_documents_expires_at'), 'documents', ['expires_at'], unique=False)
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.drop_index(op.f('ix_documents_expires_at'), table_name='documents')
    op.drop_column('documents', 'deletion_task_id')
    op.drop_column('documents', 'warning_task_id')
    op.drop_column('documents', 'expires_at')
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'is_deleted')
    # ### end Alembic commands ###
