"""added has_purchased to user table

Revision ID: 72c0f9265791
Revises: 05665c398dc2
Create Date: 2026-03-28 10:55:22.498527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c0f9265791'
down_revision: Union[str, None] = '05665c398dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_purchased', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_purchased')
    # ### end Alembic commands ###
